### ISSUE TITLE
使用默认用户名和密码无法登录

### ISSUE THREAD

**Issue by cathywife** [OneOaaS/OneOaasCmdb#1]
已按照说明进行安装，启动后能看到访问界面，然后输出默认用户名和密码无法等，后台报错如下：
[root@oneoaascmdb oneoaas-cmdb]# tailf nohup.out 
must have one register DataBase alias named `default`
2017/06/08 17:14:37 [I] [asm_amd64.s:2086] http server Running on http://:9898
2017/06/08 17:26:26 [I] [login_controller.go:102] 用户使用密码登录，使用已有token 
2017/06/08 17:26:26 [I] [login_controller.go:131] token还有效 
2017/06/08 17:26:26 [E] [base_controller.go:485] token is expired by 175h59m10s 
2017/06/08 17:26:26 [E] [base_controller.go:485] token is expired by 175h59m10s 
2017/06/08 17:28:46 [I] [login_controller.go:102] 用户使用密码登录，使用已有token 
2017/06/08 17:28:46 [I] [login_controller.go:131] token还有效 
2017/06/08 17:28:46 [E] [base_controller.go:485] token is expired by 176h1m30s 
2017/06/08 17:28:46 [E] [base_controller.go:485] token is expired by 176h1m30s

**Comment by heidsoft** [comment]
@cathywife delete from access_key; //清空下即可

**Comment by cathywife** [comment]
@heidsoft 已解决，多谢。
