### ISSUE TITLE
重启oneoaas-cmdb服务器后，oneoaas-cmdb服务无法启动，难道社区版有使用期限？还是程序问题？

### ISSUE THREAD

**Issue by cathywife** [OneOaaS/OneOaasCmdb#3]
[root@xxx oneoaas-cmdb]# sh start.sh 
[root@xxx oneoaas-cmdb]# nohup: appending output to ‘nohup.out’
[root@xxxx oneoaas-cmdb]# tailf nohup.out 
2017/07/10 16:51:54 [I] [lisence.go:141] lisence已过期 
2017/07/10 16:55:38 [I] [lisence.go:141] lisence已过期 
2017/07/10 16:56:28 [I] [lisence.go:141] lisence已过期 
2017/07/10 16:57:44 [I] [lisence.go:141] lisence已过期 
2017/07/10 17:05:57 [I] [lisence.go:141] lisence已过期

**Comment by heidsoft** [comment]
@cathywife 已经fix,感谢关注
